feat(carbon): upgrade to `v10.32`
carbon-design-system/ibm-security pull request #953
Opened 2021-04-29 10:30 UTC by SimonFinney

## Pull request - feat(carbon): upgrade to `v10.32`

### Proposed change

- Upgrade packages
- Update snapshots

2021-06-09 14:50 UTC, cameroncalder requested changes
- [ ] [Panel (v1)](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/patterns-panel--default) panels don't seem to be opening. PanelV2 works as intended.

- [ ] [CopyButton](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-copybutton--default) doesn't provide the tooltip "Copied!" feedback when the copy icon is pressed.

![image](https://user-images.githubusercontent.com/50155706/121371875-7c27cc80-c903-11eb-8699-bb6261813e7c.png)

![image](https://user-images.githubusercontent.com/50155706/121371361-1c312600-c903-11eb-8762-61d4e8753794.png)

- [ ] [NumberInput](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-numberinput--default): Seeing this error when the number value is changed with the [ -  + ]
![image](https://user-images.githubusercontent.com/50155706/121374538-95317d00-c905-11eb-9831-7aa249f5eda0.png)
![image](https://user-images.githubusercontent.com/50155706/121374709-bc884a00-c905-11eb-8d73-32b043183fa8.png)

- [ ] [OverflowMenu](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-overflowmenu--basic) text is not Plex (May be grounds to create as another issue)
![image](https://user-images.githubusercontent.com/50155706/121374969-f5282380-c905-11eb-9517-1171205bf843.png)

- [ ] [RadioButtonGroup](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-radiobuttongroup--default): There is a border drawn around the group that shouldn't be there.
![image](https://user-images.githubusercontent.com/50155706/121375677-86979580-c906-11eb-8eb7-191e6693df7a.png)

- [ ] [Tile w/ radio](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-tile--radio): There is a border drawn around the group that shouldn't be there.
![image](https://user-images.githubusercontent.com/50155706/121376521-3a008a00-c907-11eb-8d85-c7e8c1f8b0cc.png)

- [ ] [Tile w/ expandable](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-tile--expandable): Seeing this error when pressing the tile to expand.
![image](https://user-images.githubusercontent.com/50155706/121376892-864bca00-c907-11eb-8c38-2a9e661b1793.png)
![image](https://user-images.githubusercontent.com/50155706/121376956-9499e600-c907-11eb-90d8-ae5e258bf5f8.png)

2021-06-11 13:52 UTC, SimonFinney commented
> * [x]  [OverflowMenu](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-overflowmenu--basic) text is not Plex (May be grounds to create as another issue)

https://github.com/carbon-design-system/carbon/pull/8889

> * [x]  [RadioButtonGroup](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-radiobuttongroup--default): There is a border drawn around the group that shouldn't be there.

https://github.com/carbon-design-system/carbon/pull/8887

> * [x]  [Tile w/ radio](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-tile--radio): There is a border drawn around the group that shouldn't be there.

https://github.com/carbon-design-system/carbon/pull/8888

2021-06-24 13:03 UTC, Deriohig reviewed
@SimonFinney 

- [ ] Number input is giving me this error which seems different to Camerons issue : Blocked a frame with origin "https://deploy-preview-953--ibm-security.netlify.app" from accessing a cross-origin frame.


Cameron did a good job checking, I cant find any other issues other than whats still outstanding from what he has mentioned and the data table issue.

2021-06-24 13:39 UTC, SimonFinney commented
Thanks @cameroncalder / @Deriohig ! I've created a [new issue to track the deploy preview issue](https://github.com/carbon-design-system/ibm-security/issues/1021) for the remaining issues as they're all related:

> * [ ]  [Tile w/ expandable](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-tile--expandable): Seeing this error when pressing the tile to expand.
> * [ ]  [Panel (v1)](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/patterns-panel--default) panels don't seem to be opening. PanelV2 works as intended.
> * [ ]  [CopyButton](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-copybutton--default) doesn't provide the tooltip "Copied!" feedback when the copy icon is pressed.
> * [ ]  [NumberInput](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-numberinput--default): Seeing this error when the number value is changed with the [ -  + ]
> * [ ]  [OverflowMenu](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-overflowmenu--basic) text is not Plex (May be grounds to create as another issue)
> * [ ]  [Tile](https://deploy-preview-953--ibm-security.netlify.app/?path=/story/components-carbon-tile--expandable): Seeing this error when pressing the tile to expand.
> * [ ]  Number input is giving me this error which seems different to Camerons issue : Blocked a frame with origin "https://deploy-preview-953--ibm-security.netlify.app" from accessing a cross-origin frame.

Also, see [my previous comment](https://github.com/carbon-design-system/ibm-security/pull/953#issuecomment-859597785) for fixes in Carbon to the visual issues that will be absorbed in Carbon's next release.

2021-06-24 13:43 UTC, SimonFinney commented on src/components/DataTable/__tests__/__snapshots__/DataTable.spec.js.snap
> +                        className="bx--data-table bx--data-table--normal bx--data-table--no-border"
https://github.com/carbon-design-system/ibm-security/issues/1020

2021-06-25 07:34 UTC, Deriohig approved these changes
Looks good, some merge conflicts with dev that need to be fixed tho!

2021-06-25 10:47 UTC, merged

2021-06-25 11:01 UTC, SimonFinney commented
:tada: This PR is included in version 1.43.0-prerelease.3 :tada:

The release is available on:
- [npm package (@canary dist-tag)](https://www.npmjs.com/package/@carbon/ibm-security/v/1.43.0-prerelease.3)
- [GitHub release](https://github.com/carbon-design-system/ibm-security/releases/tag/v1.43.0-prerelease.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-07-02 10:39 UTC, SimonFinney commented
:tada: This PR is included in version 1.43.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@carbon/ibm-security/v/1.43.0)
- [GitHub release](https://github.com/carbon-design-system/ibm-security/releases/tag/v1.43.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: